export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const GET_PROJECTS_BEGIN = 'GET_PROJECTS_BEGIN'
export const GET_PROJECT_BEGIN_NO_LOADING = 'GET_PROJECT_BEGIN_NO_LOADING'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'

export const GET_PROJECT_BEGIN = 'GET_PROJECT_BEGIN'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'

export const EDIT_PROJECT_BEGIN = 'EDIT_PROJECT_BEGIN'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_BEGIN'

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'

export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_ERROR = 'EDIT_TASK_BEGIN'

export const ADD_USER_BEGIN = 'ADD_USER_BEGIN'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'